//near_animals
action_rabbit = player addaction ["Harvest Rabbit","harvestAnimal.sqf","rabbit",1,true,true,"",'if (!near_animals) then {false} else {near_rabbit = (nearestobjects [player, ["Rabbit_F"],  3] select 0); if (isnil "near_rabbit") then {false} else {_inuse = near_rabbit getvariable "inuse"; isnil "_inuse" and player distance near_rabbit < 5 and !alive near_rabbit}}'];
action_snake = player addaction ["Harvest Snake","harvestAnimal.sqf","snake",1,true,true,"",'if (!near_animals) then {false} else {near_snake = (nearestobjects [player, ["Snake_random_F"],  3] select 0); if (isnil "near_snake") then {false} else {_inuse = near_snake getvariable "inuse"; isnil "_inuse" and player distance near_snake < 5 and !alive near_snake}}'];
action_turtle = player addaction ["Harvest Turtle","harvestAnimal.sqf","turtle",1,true,true,"",'if (!near_animals) then {false} else {near_turtle = (nearestobjects [player, ["Turtle_F"],  3] select 0); if (isnil "near_turtle") then {false} else {_inuse = near_turtle getvariable "inuse"; isnil "_inuse" and player distance near_turtle < 5 and !alive near_turtle}}'];
action_fish = player addaction ["Harvest Fish","harvestAnimal.sqf","fish",1,true,true,"",'if (!near_animals) then {false} else {near_fish = (nearestobjects [player, fishtypes,  3] select 0); if (isnil "near_fish") then {false} else {_inuse = near_fish getvariable "inuse"; isnil "_inuse" and player distance near_fish < 5 and !alive near_fish}}'];
action_sheep = player addaction ["Harvest Sheep","harvestAnimal.sqf","sheep",1,true,true,"",'if (!near_animals) then {false} else {near_sheep = (nearestobjects [player, ["Sheep_random_F"],  3] select 0); if (isnil "near_sheep") then {false} else {_inuse = near_sheep getvariable "inuse"; isnil "_inuse" and player distance near_sheep < 5 and !alive near_sheep}}'];

//near_vehicles
action_pullout = player addaction ["Pull out","gc\client\GC_FNC_noScript.sqf",'(nearestobjects [player, ["Air", "Ship", "LandVehicle"], 4] select 0) execVM "pullout.sqf";',1,true,true,"",'if (!near_vehicles) then {false} else {near_vehicle_p = (nearestobjects [player, ["Air", "Ship", "LandVehicle"], 4] select 0);if (isnil "near_vehicle_p") then {false} else {player distance near_vehicle_p < 5 and count (crew near_vehicle_p) > 0 and near_vehicle_p in INV_ServerVclArray and (call INV_isArmed) and near_vehicle_p != vehicle player}}'];
action_putin = player addaction ["Load player in car","gc\client\GC_FNC_noScript.sqf",'(nearestobjects [player, ["Air", "Ship", "LandVehicle"], 8] select 0) execVM "gc\client\GC_PutIn.sqf";',1,true,true,"",'if (!near_vehicles or !gc_tiedplayer) then {false} else {near_vehicle_h = (nearestobjects [player, ["Air", "Ship", "LandVehicle"], 8] select 0);if (isnil "near_vehicle_h") then {false} else {player distance near_vehicle_h < 8 and near_vehicle_h in INV_ServerVclArray and ([] call INV_isArmed) and near_vehicle_h != vehicle player}}'];
action_info = player addaction [localize "STRS_addAction_vehicleinfo","gc\client\GC_FNC_noScript.sqf",'(nearestobjects [player, ["Air", "Ship", "LandVehicle"], 4] select 0) execVM "vehinfo.sqf";',1,true,true,"",'if (!near_vehicles) then {false} else {near_vehicle_i = (nearestobjects [player, ["Air", "Ship", "LandVehicle","Tank"], 4] select 0);if(isnil "near_vehicle_i") then {false} else {player distance near_vehicle_i < 5 and near_vehicle_i in INV_ServerVclArray and near_vehicle_i != vehicle player}}'];
action_unflip = player addaction ["Unflip vehicle","unflipvehicle.sqf",["unflip"],1,false,true,"",'if (!near_vehicles) then {false} else {near_vehicle_f = (nearestobjects [player, ["Air", "Ship", "LandVehicle"], 4] select 0);if (isnil "near_vehicle_f") then {false} else {player distance near_vehicle_f < 5 and near_vehicle_f in INV_VehicleArray and near_vehicle_f != vehicle player}}'];

//near_objects
action_remove_corner = player addaction ["Remove Big bag fence (corner)","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("BigbagfenceCorner" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_bagfence_corner_F"],  3] select 0);["BigbagfenceCorner", 1] call INV_AddInventoreItem;player groupchat "You picked up a sandbag wall (corner)!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_bagfence_corner_F"],  3] select 0) < 5}'];
action_remove_fence = player addaction ["Remove Big bag fence","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("bigbagfence" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_bagfence_long_F"],  3] select 0);["bigbagfence", 1] call INV_AddInventoreItem;player groupchat "You picked up a sandbag wall!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_bagfence_long_F"],  3] select 0) < 5 and player distance terrornpc > 30}'];
action_remove_round = player addaction ["Remove Big bag fence (round)","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("bigbagfenceRound" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_bagfence_round_F"],  3] select 0);["bigbagfenceRound", 1] call INV_AddInventoreItem;player groupchat "You picked up a sandbag wall (round)!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_bagfence_round_F"],  3] select 0) < 5 and player distance terrornpc > 30}'];
action_remove_bunker = player addaction ["Remove Bunker (small)","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("bunkersmall" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_BagBunker_small_F"],  3] select 0);["bunkersmall", 1] call INV_AddInventoreItem;player groupchat "You picked up a bunker (small)!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_BagBunker_small_F"],  3] select 0) < 5}'];
action_remove_danger = player addaction ["Remove Danger Sign","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("danger" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_Sign_Mines_F"],  3] select 0);["danger", 1] call INV_AddInventoreItem;player groupchat "You picked up a danger sign!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_Sign_Mines_F"],  3] select 0) < 5}'];
action_remove_static1 = player addaction ["Remove HMG Static","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("O_HMG_01_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["O_HMG_01_F"],  3] select 0);["O_HMG_01_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a static HMG!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["O_HMG_01_F"],  3] select 0) < 5}'];
action_remove_static2 = player addaction ["Remove GMG Static","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("O_GMG_01_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["O_GMG_01_F"],  3] select 0);["O_GMG_01_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a static GMG!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["O_GMG_01_F"],  3] select 0) < 5}'];
action_remove_static3 = player addaction ["Remove Mk6 Mortar","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("O_Mortar_01_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["O_Mortar_01_F"],  3] select 0);["O_Mortar_01_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a mortar launcher!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["O_Mortar_01_F"],  3] select 0) < 5}'];
action_remove_static4 = player addaction ["Remove HMG Static","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("B_HMG_01_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["B_HMG_01_F"],  3] select 0);["B_HMG_01_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a static HMG!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["B_HMG_01_F"],  3] select 0) < 5}'];
action_remove_static5 = player addaction ["Remove GMG Static","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("B_GMG_01_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["B_GMG_01_F"],  3] select 0);["B_GMG_01_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a static GMG!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["B_GMG_01_F"],  3] select 0) < 5}'];
action_remove_static6 = player addaction ["Remove Mk6 Mortar","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("B_Mortar_01_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["B_Mortar_01_F"],  3] select 0);["B_Mortar_01_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a mortar launcher!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["B_Mortar_01_F"],  3] select 0) < 5}'];
action_remove_static7 = player addaction ["Remove Titan Laauncher","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("I_static_AT_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["I_static_AT_F"],  3] select 0);["I_static_AT_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a titan launcher!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["I_static_AT_F"],  3] select 0) < 5}'];
action_remove_static8 = player addaction ["Remove Titan Laauncher","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("I_static_AA_F" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["I_static_AA_F"],  3] select 0);["I_static_AA_F", 1] call INV_AddInventoreItem;player groupchat "You picked up a titan launcher!";',1,true,true,"",'if (!near_objects) then {false} else {player distance (nearestobjects [player, ["I_static_AA_F"],  3] select 0) < 5}'];

//fast travel desks
action_ft1_laptop = ftlaptop1 addaction ["Use Laptop","gc\client\GC_FastTravel.sqf",[marina],1,false,true,"","_this distance ftlaptop1 <= 4"];
action_ft1_desk = ftdesk1 addaction ["Use Laptop","gc\client\GC_FastTravel.sqf",[marina],1,false,true,"","_this distance ftlaptop1 <= 4"];
action_ft2_laptop = ftlaptop2 addaction ["Use Laptop","gc\client\GC_FastTravel.sqf",[girna],1,false,true,"","_this distance ftlaptop2 <= 4"];
action_ft2_desk = ftdesk2 addaction ["Use Laptop","gc\client\GC_FastTravel.sqf",[girna],1,false,true,"","_this distance ftlaptop2 <= 4"];

//cops
if (iscop) then {
  //near_spikes
  action_spikes = player addaction ["Remove spike strip", "gc\client\GC_FNC_noScript.sqf",'deletevehicle (nearestobjects [ player, ["Land_Razorwire_F"],  6] select 0);',1,true,true,"",'near_spikes'];

  //near_evidence
  action_evidence = player addaction ["Take evidence","gc\client\GC_FNC_noScript.sqf",'["GC_Hand",["CHAOS LIFE POLICE","You have removed the evidence!"]] spawn bis_fnc_showNotification; {deletevehicle _x} foreach (nearestobjects [player, ["groundWeaponHolder"], 4])',1,true,true,"",'near_evidence and !isStunned;'];

  //near_slaves
  action_question = player addaction ["Who is your pimp?","gc\client\GC_FNC_noScript.sqf",'["GC_Talk",["CHAOS LIFE POLICE", format["this prostitute works for %1.", leader (nearestobjects [player, civprostitutearray,  3] select 0)]]] spawn bis_fnc_showNotification;',1,true,true,"",'if(!near_slaves) then {false} else {near_slave_q = (nearestobjects [player, civprostitutearray, 3] select 0); if (isnil "near_slave_q") then {false} else { !(near_slave_q in playerarray) and player distance near_slave_q < 5 and (leader near_slave_q) in playerarray}}'];
  action_free = player addaction ["Set prostitute free","gc\client\GC_FNC_noScript.sqf",'_slave = (nearestobjects [player, civprostitutearray,  3] select 0); _civ = leader _slave; deletevehicle _slave; (format ["[""Prostitute"", %1] spawn Isse_AddCrimeLogEntry; if(!(""being a pimp"" in %1_reason))then{%1_reason = %1_reason + [""being a pimp""]}; %1_wanted = 1; kopfcash_%1 = kopfcash_%1 + 20000;", _civ]) call broadcast;["GC_Good2",["CHAOS LIFE POLICE","You have freed the prositute from a life of whoring!"]] spawn bis_fnc_showNotification;',1,true,true,"",'if (!near_slaves) then {false} else {near_slave_f = (nearestobjects [player, civprostitutearray, 3] select 0); if (isnil "near_slave_f") then {false} else { !(near_slave_f in playerarray) and player distance near_slave_f < 5 and (leader _slave) in playerarray}}'];

  //near_vehicles
  action_check = player addaction [localize "STRS_addaction_trunk_see","gc\client\GC_FNC_noScript.sqf",'_vcl = (nearestobjects [player, ["Air", "Ship", "LandVehicle","Tank"], 4] select 0);_str = format["%1_storage", _vcl];[_str] execVM "vehiclecheck.sqf";',1,true,true,"",'if(!near_vehicles) then {false} else {near_vehicle_t = (nearestobjects [player, ["Air", "Ship", "LandVehicle"], 4] select 0); if (isnil "near_vehicle_t") then {false} else {player distance near_vehicle_t < 5 and !(near_vehicle_t in INV_VehicleArray) and near_vehicle_t in INV_ServerVclArray and near_vehicle_t != vehicle player}}'];
  action_searchs = player addaction [localize "STRS_addaction_trunk_check","gc\client\GC_FNC_noScript.sqf",'_vcl = (nearestobjects [player, ["Air", "Ship", "LandVehicle","Tank"], 4] select 0);_str = format["%1_storage", _vcl];if([_vcl,_str] call INV_RemoveIllegalStorage)then{call compile format["publicvariable ""%1"";", _str]};',1,true,true,"",'if(!near_vehicles) then {false} else {near_vehicle_c = (nearestobjects [player, ["Air", "Ship", "LandVehicle"], 4] select 0); if (isnil "near_vehicle_c") then {false} else {player distance near_vehicle_c < 5 and !(near_vehicle_c in INV_VehicleArray) and near_vehicle_c in INV_ServerVclArray and near_vehicle_c != vehicle player}}'];
  action_impound = player addaction ["Impound vehicle","gc\client\GC_FNC_noScript.sqf",'_vcl = (nearestobjects [player, ["LandVehicle","Tank"], 4] select 0);  [_vcl, "impound"] execVM "impound.sqf";',1,true,true,"",'if(!near_vehicles) then {false} else {near_vehicle_v = (nearestobjects [player, ["LandVehicle"], 4] select 0);if (isnil "near_vehicle_v") then {false} else {player distance near_vehicle_v < 5 and near_vehicle_v in INV_ServerVclArray and near_vehicle_v != vehicle player}}'];
  action_impound2 = player addaction ["Impound aircraft","gc\client\GC_FNC_noScript.sqf",'_vcl = (nearestobjects [player, ["Air"], 4] select 0); [_vcl, "impound2"] execVM "impound2.sqf";',1,true,true,"",'if(!near_vehicles) then {false} else {near_vehicle_a = (nearestobjects [player, ["Air"], 4] select 0);if (isnil "near_vehicle_a") then {false} else {player distance near_vehicle_a < 5 and near_vehicle_a in INV_ServerVclArray and near_vehicle_a != vehicle player}}'];
  action_impound3 = player addaction ["Impound boat","gc\client\GC_FNC_noScript.sqf",'_vcl = (nearestobjects [player, ["Ship"], 6] select 0); [_vcl, "impound3"] execVM "impound3.sqf";',1,true,true,"",'if(!near_vehicles) then {false} else {near_vehicle_z = (nearestobjects [player, ["Ship"], 6] select 0);if (isnil "near_vehicle_z") then {false} else {player distance near_vehicle_z <= 6 and near_vehicle_z in INV_ServerVclArray and near_vehicle_z != vehicle player}}'];

  //near_objects
  action_bargate = player addaction ["Open/close gate","gc\client\GC_FNC_noScript.sqf",'_gate = (nearestobjects [player, ["Land_BarGate_F"],  10] select 0); if(_gate animationPhase "bargate" == 1)then{_gate animate ["bargate", 0]}else{_gate animate ["bargate", 1]};',1,true,true,"",'if(!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_BarGate_F"],  10] select 0) < 7}'];
  action_remove_roadblock = player addaction ["Remove Roadblock","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("roadblock" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_Crash_barrier_F"],  3] select 0);["roadblock", 1] call INV_AddInventoreItem;player groupchat "you picked up a roadblock";',1,true,true,"",'if(!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_Crash_barrier_F"],  3] select 0) < 5}'];
  action_remove_bargate = player addaction ["Remove Bargate","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("Bargate" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_BarGate_F"],  10] select 0);["Bargate", 1] call INV_AddInventoreItem;player groupchat "you picked up a bargate";',1,true,true,"",'if(!near_objects) then {false} else {player distance (nearestobjects [ player, ["Land_BarGate_F"],  10] select 0) < 7}'];
  action_remove_cone = player addaction ["Remove Road Cone","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("roadcone" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["RoadCone_L_F"],  3] select 0);["roadcone", 1] call INV_AddInventoreItem;player groupchat "you picked up a road cone";',1,true,true,"",'if(!near_objects) then {false} else {player distance (nearestobjects [player, ["RoadCone_L_F"],  3] select 0) < 5}'];
  action_remove_barrier = player addaction ["Remove Hbarrier","gc\client\GC_FNC_noScript.sqf",'if (((call INV_GetOwnWeight) + ("Hbarrier" call INV_getitemTypeKg)) > INV_Tragfaehigkeit)exitwith{player groupChat localize "STRS_inv_buyitems_maxgewicht"};deletevehicle (nearestobjects [player, ["Land_HBarrier_5_F"],  3] select 0);["Hbarrier", 1] call INV_AddInventoreItem;player groupchat "you picked up a HBarrier";',1,true,true,"",'if(!near_objects) then {false} else {player distance (nearestobjects [player, ["Land_HBarrier_5_F"],  3] select 0) < 5}'];
};

// wait 5 then reset busy flags in case they were stuck
if (doingSomething or shopactivescript) then {
  [] spawn {
    sleep 5;
    doingSomething = false;
    shopactivescript = false;
  };
};
